sculpture/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path("about/", views.AboutView.as_view(), name="about"),
    path("news/", views.NewsView.as_view(), name="news"),
    path("<slug:slug>/pay/", views.PaySculptureView.as_view(), name='pay_sculpture'),
    path("free/sculpture/", views.DevSculptureView.as_view(), name='development_list'),
    path("free/portals/", views.DevPortalView.as_view(), name='development_list'),
    path("sculpture/", views.SculptureView.as_view(), name='sculpture_list'),
    path("portals/", views.PortalView.as_view(), name='portals_list'),
    path("dev/<slug:slug>/", views.DevSculptureDetailView.as_view(), name='development'),
    path("<slug:slug>/", views.SculptureDetailView.as_view(), name="sculpture_detail"),
    path("review/<int:pk>/", views.AddReview.as_view(), name="add_review"),
    path("order/<int:pk>/", views.NewOrder.as_view(), name="new_order"),

]

sokyrenko/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('pages/', include('django.contrib.flatpages.urls')),
    path('', include("sculpture.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sculpture/models.py
from ckeditor_uploader.fields import RichTextUploadingField
from django.db import models
from datetime import date
from django.utils import timezone

from django.urls import reverse


class Category(models.Model):
    """Категория"""
    name = models.CharField("Категория", max_length=150)
    description = models.TextField("Описание")
    url = models.SlugField(max_length=160)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Категория"
        verbose_name_plural = "Категории"


class Author(models.Model):
    """Автор"""
    name = models.CharField("Имя", max_length=100)
    age = models.PositiveSmallIntegerField('Возраст', default=0)
    description = models.TextField("Описание")
    image = models.ImageField("Изображение", upload_to="author/")

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Автор"
        verbose_name_plural = "Автора"


class Sculpture(models.Model):
    """Скульптура"""
    draft = models.BooleanField("Деактивировать на сайте", default=False)
    title = models.CharField("Название", max_length=100)
    tagline = models.CharField("Слоган", max_length=100, default='')
    url = models.SlugField("Ссылка", max_length=160, unique=True)
    category = models.ForeignKey(Category, verbose_name='Категория', on_delete=models.SET_NULL, null=True)
    author = models.ManyToManyField(Author, verbose_name="Автор", related_name='sculpture_author')
    description = RichTextUploadingField("Описание")
    image_title = models.ImageField("Фото изделия", upload_to='image_title/')
    files = models.FileField(verbose_name='Архив с фото', default="", upload_to='files/', blank=True)
    presence = models.CharField("Наличие", max_length=30, blank=True)
    complectation = models.CharField("Комплектация", max_length=99, default='', blank=True)
    production_time = models.CharField("Срок изготовления", max_length=30, blank=True)
    price = models.IntegerField("Цена", default='12000', blank=True)
    old_price = models.IntegerField("Старая цена", blank=True, null=True)
    valute = models.CharField("Валюта", default='грн', max_length=10, blank=True, null=True)

    year = models.DateField("Изделие создано", default=date.today, blank=True)
    material = models.CharField("Материал", max_length=60, blank=True)
    gabarits = models.CharField("Габариты", max_length=30, blank=True)
    conditions = RichTextUploadingField("Условия заказа", blank=True)
    delivery = RichTextUploadingField("Доставка", blank=True)

    meta_keywords = models.TextField("meta name=\"keywords\" content ", default='', blank=True)
    meta_description = models.TextField("meta name=\"description\" content ", default='', blank=True)

    def __str__(self):
        return f'{self.title}'

    def get_absolute_url(self):
        return reverse("sculpture_detail", kwargs={"slug": self.url})

    def get_review(self):
        return self.reviews_set.filter(parent__isnull=True)

    class Meta:
        verbose_name = "Изделие"
        verbose_name_plural = "Изделия | Каталог"


class ImageSculpture(models.Model):
    """Изображения скульптуры"""
    title = models.CharField("Название", max_length=100)
    description = models.TextField("Описание")
    image = models.ImageField("Изображение", upload_to="image_sculpture/")
    sculpture = models.ForeignKey(Sculpture, verbose_name="Изделие", on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.sculpture} - {self.title}'

    class Meta:
        verbose_name = "Изображение"
        verbose_name_plural = "Изображения | Католог"


class ImageHome(models.Model):
    """слайдер на главной"""
    draft = models.BooleanField("Деактивировать на сайте", default=False)
    title = RichTextUploadingField("Заголовок", max_length=100)
    up_title = models.CharField("Подзаголовок", max_length=100)
    image = models.ImageField("Изображение", upload_to="image_home/")
    sculpture = models.ForeignKey(Sculpture, verbose_name="Изделие", on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.sculpture}'

    class Meta:
        verbose_name = "Слайд"
        verbose_name_plural = "Слайды на главной"


class News(models.Model):
    draft = models.BooleanField("Деактивировать на сайте", default=False)
    title = models.CharField("Имя", max_length=100)
    text = RichTextUploadingField("Сообщение", max_length=5000)
    image = models.ImageField("Изображение", upload_to="news/")
    year = models.DateField("Дата публикации", default=date.today)

    def __str__(self):
        return f'{self.title} - {self.year}'

    class Meta:
        verbose_name = "Новость"
        verbose_name_plural = "Новости"


class Reviews(models.Model):
    """Отзывы"""
    email = models.EmailField()
    name = models.CharField("Имя", max_length=100)
    text = models.TextField("Сообщение", max_length=5000)
    parent = models.ForeignKey('self', verbose_name='Родитель', on_delete=models.SET_NULL, blank=True, null=True)
    sculpture = models.ForeignKey(Sculpture, verbose_name="Изделие", on_delete=models.CASCADE)
    year = models.DateField("Дата отзыва", default=date.today, blank=True)

    def __str__(self):
        return f"{self.sculpture} - {self.name}"

    class Meta:
        verbose_name = "Отзыв"
        verbose_name_plural = "Отзывы"


class Development(models.Model):
    """Скульптура разработка"""
    draft = models.BooleanField("Деактивировать на сайте", default=False)
    title = models.CharField("Название", max_length=100)
    tagline = models.CharField("Слоган", max_length=100, default='')
    url = models.SlugField("Ссылка", max_length=160, unique=True)
    category = models.ForeignKey(Category, verbose_name='Категория', on_delete=models.SET_NULL, null=True)

    description = RichTextUploadingField("Описание")
    image_title = models.ImageField("Фото изделия", upload_to='image_title/')

    meta_keywords = models.TextField("Meta name=\"keywords\" content ", default='', blank=True)
    meta_description = models.TextField("Meta name=\"description\" content ", default='', blank=True)

    def __str__(self):
        return f'{self.title}'

    def get_absolute_url(self):
        return reverse("development", kwargs={"slug": self.url})

    class Meta:
        verbose_name = "Изделие"
        verbose_name_plural = "Изделия | Мастерская"


class ImageDevelopment(models.Model):
    """Изображения скульптуры"""
    title = models.CharField("Название", max_length=100)
    description = models.TextField("Описание")
    image = models.ImageField("Изображение", upload_to="image_sculpture/")
    sculpture = models.ForeignKey(Development, verbose_name="Изделие", on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.sculpture} - {self.title}'

    class Meta:
        verbose_name = "Изображение"
        verbose_name_plural = "Изображения | Мастерская"


class PlaceOder(models.Model):
    """Оформить заказ"""
    email = models.EmailField()
    first_name = models.CharField("Имя", max_length=30, default='')
    last_name = models.CharField("Фамилия", max_length=50, default='')
    phone = models.CharField("Телефон", max_length=13)
    text = models.TextField("Сообщение", max_length=5000, default='', blank=True)
    sculpture = models.ForeignKey(Sculpture, verbose_name="Изделие", on_delete=models.CASCADE)
    year = models.DateTimeField("Дата заказа", default=timezone.now, blank=True)

    def __str__(self):
        return f"{self.first_name} - {self.sculpture}"

    class Meta:
        verbose_name = "Заказ"
        verbose_name_plural = "Заказы"

sculpture/forms.py
from django import forms

from .models import Reviews, PlaceOder


class ReviewForm(forms.ModelForm):
    """Форма отзыва"""
    class Meta:
        model = Reviews
        fields = ('name', 'email', 'text')


class NewOrderForm(forms.ModelForm):
    """Форма заказа"""
    class Meta:
        model = PlaceOder
        fields = ('first_name', 'last_name', 'phone', 'email', 'text')

sculpture/views.py
from django.shortcuts import render, redirect
from django.views.generic import ListView, DetailView
from django.views.generic.base import View

from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
import smtplib

from .models import Sculpture, ImageHome, News, Author, Development
from .forms import ReviewForm, NewOrderForm


def massage_email(massages, theme):
    # create message object instance
    msg = MIMEMultipart()
    message = massages

    # setup the parameters of the message
    password = "234ft0ph8isoargt234AS-09sd"
    msg['From'] = "quality.figures.shop@gmail.com"
    msg['To'] = "kostencko.alexander2012@gmail.com"
    msg['Subject'] = theme

    # add in the message body
    msg.attach(MIMEText(message, 'plain'))
    # create server
    server = smtplib.SMTP('smtp.gmail.com: 587')
    server.starttls()

    # Login Credentials for sending the mail
    server.login(msg['From'], password)

    # send the message via the server.
    server.sendmail(msg['From'], msg['To'], msg.as_string())
    server.quit()
    print("successfully sent email to %s:" % (msg['To']))


class IndexView(ListView):
    """главная"""
    model = ImageHome
    queryset = ImageHome.objects.filter(draft=False)
    template_name = "sculptures/index.html"


class AboutView(ListView):
    """О нас"""
    model = Author
    queryset = Author.objects.all()
    template_name = "sculptures/about.html"


class NewsView(ListView):
    """Новости"""
    model = News
    queryset = model.objects.filter(draft=False).order_by('-year')
    template_name = "sculptures/news.html"


class SculptureView(ListView):
    """список скульптур"""
    model = Sculpture
    queryset = Sculpture.objects.filter(draft=False, category__url='sculpture')
    template_name = "sculptures/sculpture_list.html"


class PortalView(ListView):
    """список порталов"""
    model = Sculpture
    queryset = Sculpture.objects.filter(draft=False, category__url='portals')
    template_name = "sculptures/portals_list.html"


class SculptureDetailView(DetailView):
    """полное описание скульптуры"""
    model = Sculpture
    slug_field = "url"
    template_name = "sculptures/sculpture_detail.html"


class AddReview(View):
    """Отзывы"""
    def post(self, request, pk):
        form = ReviewForm(request.POST)
        sculpture = Sculpture.objects.get(id=pk)
        if form.is_valid():
            form = form.save(commit=False)
            if request.POST.get("parent", None):
                form.parent_id = int(request.POST.get("parent"))
            form.sculpture = sculpture
            form.save()

        message = """
        ┏─══─━══─⊱ <:─══──:> ⊰─══━─══─┓
                    %s
        ┗─══─━══─⊱ <:─══──:> ⊰─══━─══─┛
        
        ╔═════════════════════════════╗
        ║ Имя: ➳ %s
        ║ ────────────────────────────
        ║ Email: ➳ %s
        ║ ────────────────────────────
        ║ Сообщение: ⤵
        ║ ────────────────────────────
        ║ ✎ %s
        ╚═════════════════════════════╝
                   """ % (sculpture.title, form.name, form.email, form.text)

        theme = "Отзыв на сайте"
        massage_email(message, theme)

        return redirect(sculpture.get_absolute_url())


class DevSculptureView(ListView):
    """список скульптур | мастервкая"""
    model = Development
    queryset = Development.objects.filter(draft=False, category__url='free_sculpture')
    template_name = "sculptures/dev_sculpture_list.html"


class DevSculptureDetailView(DetailView):
    """полное описание скульптуры | мастервкая"""
    model = Development
    slug_field = "url"
    template_name = "sculptures/dev_sculpture_detail.html"


class DevPortalView(ListView):
    """список скульптур | мастервкая"""
    model = Development
    queryset = Development.objects.filter(draft=False, category__url='free_portals')
    template_name = "sculptures/dev_portal_list.html"


class PaySculptureView(View):
    def get(self, request, slug):
        sculpture = Sculpture.objects.get(url=slug)
        return render(request, "sculptures/pay_sculpture.html", {"sculpture": sculpture})


class NewOrder(View):
    """заказ"""
    def post(self, request, pk):
        form = NewOrderForm(request.POST)
        sculpture = Sculpture.objects.get(id=pk)
        if form.is_valid():
            form = form.save(commit=False)
            form.sculpture = sculpture
            form.save()

            message = """     
            ┏─══─━══─⊱ <:─══──:> ⊰─══━─══─┓
                        %s
            ┗─══─━══─⊱ <:─══──:> ⊰─══━─══─┛  
    
            ╔═════════════════════════════╗
            ║ Имя: ➳ %s
            ║ ────────────────────────────
            ║ Фамилия: ➳ %s
            ║ ────────────────────────────
            ║ Телефон: ➳ %s
            ║ ────────────────────────────
            ║ Email: ➳ %s
            ║ ────────────────────────────
            ║ Сообщение: ⤵ 
            ║ ────────────────────────────
            ║ %s
            ╚═════════════════════════════╝
            
                      """ % (sculpture.title, form.first_name, form.last_name, form.phone, form.email, form.text)

            theme = "•——◤✧Заказ на сайте✧◥——•"
            massage_email(message, theme)

        return render(request, "sculptures/successfully.html", {"sculpture": sculpture})

templates/sculptures/base.html
{% extends 'base.html' %}

{% block content %}

{% endblock content %}

templates/sculptures/dev_portal_list.html
{% extends 'sculptures/base.html' %}

{% load static %}

{% block title %} Порталы {% endblock title %}

{%  block content %}

    <section class="mbr-section article content9 cid-rUKj6z2paH" id="content9-2v">
        <div class="container">
            <div class="inner-container" style="width: 100%;">
                <hr class="line" style="width: 25%;">
                <div class="section-text align-center mbr-fonts-style display-2">
                    Порталы
                </div>
                <hr class="line" style="width: 25%;">
            </div>
        </div>
    </section>

    <section class="services1 cid-rW8nkLhdWM" id="services1-37">
        <div class="container">
            <div class="row justify-content-center">
                <div class="title pb-5 col-12"></div>

                {% for dev in development_list %}

                    <div class="card col-12 col-md-6 p-3 col-lg-4">
                        <div class="card-wrapper">
                            <div class="card-img">
                                <img src="{{ dev.image_title.url }}" alt="">
                            </div>
                            <div class="card-box">
                                <h4 class="card-title mbr-fonts-style display-5">
                                    {{ dev.title }}
                                </h4>
                                <div class="mbr-section-btn align-center">
                                    <a href="{{ dev.get_absolute_url }}" class="btn btn-primary display-4">
                                        Подробнее
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>

                {% endfor %}

            </div>
        </div>
    </section>

{% endblock content %}

templates/sculptures/dev_sculpture_detail.html
{% extends 'sculptures/base.html' %}

{% block keywords %} {{ sculpture.meta_keywords }} {% endblock keywords %}

{% block description %} {{ sculpture.meta_description }} {% endblock description %}

{% block title %} {{ development.title }} {% endblock title %}

{% load static %}

{% block content %}

    <section class="mbr-section article content9 cid-rUKjGovGR9" id="content9-2w">
        <div class="container">
            <div class="inner-container" style="width: 100%;">
                <hr class="line" style="width: 25%;">
                <div class="section-text align-center mbr-fonts-style display-1">
                    {{ development.title }}
                </div>
                <hr class="line" style="width: 25%;">
            </div>
        </div>
    </section>

    <section class="services2 cid-rUJZ1h8NOj" id="services2-28">
        <div class="container">
            <div class="col-md-12">
                <div class="media-container-row">
                    <div class="mbr-figure" style="width: 65%;">
                        <div class="owl-carousel owl-theme" id="slider">

                            {% for image in development.imagedevelopment_set.all %}
                                <div class="item ">
                                    <a href="{{ image.image.url }}" data-fancybox="">
                                        <img src="{{ image.image.url }}">
                                    </a>
                                </div>
                            {% endfor %}

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <section class="mbr-section article content9 cid-rUIDwpcuQ4" id="content9-1k">
        <div class="container">
            <div class="inner-container" style="width: 100%;">
                <hr class="line" style="width: 25%;">
                <div class="section-text align-center mbr-fonts-style display-2">Описание</div>
                <hr class="line" style="width: 25%;">
            </div>
        </div>
    </section>

    <section class="mbr-section article content1 cid-rUJXxcJXJx" id="content1-27">
        <div class="container">
            <div class="media-container-row">
                <div class="mbr-text col-12 mbr-fonts-style display-7 col-md-12">
                    <p>
                        {{ development.description|safe }}
                    </p>
                </div>
            </div>
        </div>
    </section>

{% endblock content %}

templates/sculptures/dev_sculpture_list.html
{% extends 'sculptures/base.html' %}

{% load static %}

{% block title %} Скульптуры {% endblock title %}

{%  block content %}

    <section class="mbr-section article content9 cid-rUKj6z2paH" id="content9-2v">
        <div class="container">
            <div class="inner-container" style="width: 100%;">
                <hr class="line" style="width: 25%;">
                <div class="section-text align-center mbr-fonts-style display-2">
                    Скульптуры
                </div>
                <hr class="line" style="width: 25%;">
            </div>
        </div>
    </section>

    <section class="services1 cid-rW8nkLhdWM" id="services1-37">
        <div class="container">
            <div class="row justify-content-center">
                <div class="title pb-5 col-12"></div>

                {% for dev in development_list %}

                    <div class="card col-12 col-md-6 p-3 col-lg-4">
                        <div class="card-wrapper">
                            <div class="card-img">
                                <img src="{{ dev.image_title.url }}" alt="">
                            </div>
                            <div class="card-box">
                                <h4 class="card-title mbr-fonts-style display-5">
                                    {{ dev.title }}
                                </h4>
                                <div class="mbr-section-btn align-center">
                                    <a href="{{ dev.get_absolute_url }}" class="btn btn-primary display-4">
                                        Подробнее
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>

                {% endfor %}

            </div>
        </div>
    </section>

{% endblock content %}

templates/sculptures/news.html
{% extends 'sculptures/base.html' %}

{% block title %} Новости {% endblock title %}

{% load static %}

{% block content %}

    <section class="mbr-section article content9 cid-rUKd4eCwpu" id="content9-2o">
        <div class="container">
            <div class="inner-container" style="width: 100%;">
                <hr class="line" style="width: 25%;">
                <div class="section-text align-center mbr-fonts-style display-2">Новости</div>
                <hr class="line" style="width: 25%;">
            </div>
        </div>
    </section>

    <section class="services4 cid-rX4c3bAdFg" id="services4-4a">
        <div class="container">
            <div class="row">

                {% for item in news_list %}

                    <div class="card p-3 col-12">
                        <div class="card-wrapper media-container-row media-container-row">
                            <div class="card-box">
                                <div class="row">
                                    <div class="col-12 col-md-12 col-lg-4">
                                        <div class="wrapper">
                                            <!--Image-->
                                            <div class="mbr-figure" style="width: 100%;">
                                                <img src="{{ item.image.url }}" alt="">
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-12 col-md-7 col-lg-4">
                                        <div class="wrapper col-left">
                                            <!--Title-->
                                            <h4 class="card-title mbr-fonts-style display-5">
                                                {{ item.title }}
                                            </h4>
                                            <!--Subtitle-->
                                            <p class="mbr-text mbr-fonts-style pt-3 display-7">
                                                {{ item.text|safe }}
                                            </p>
                                        </div>
                                    </div>
                                    <div class="col-12 col-md-5 col-lg-4">
                                        <div class="wrapper border_wrapper">
                                            <!--Cost-->
                                            <p class="mbr-text mbr-fonts-style col-right mbr-black align-center display-6">
                                                {{ item.year }}
                                            </p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>

                {% endfor %}

            </div>
        </div>
    </section>

{% endblock content %}

templates/sculptures/pay_sculpture.html
{% extends 'sculptures/base.html' %}

{% load static %}

{% block title %} Оформление заказа {% endblock title %}

{%  block content %}

    <section class="mbr-section form1 cid-rUIK7kRu1d" id="form1-1r">
        <div class="container">
            <div class="row justify-content-center">
                <div class="title col-12 col-lg-8">
                    <h2 class="mbr-section-title align-center pb-3 mbr-fonts-style display-2">Оформить заказ на:</h2>
                    <h2 class="mbr-section-title align-center pb-3 mbr-fonts-style display-2">"{{ sculpture.title }}"</h2>

                </div>
            </div>
        </div>

        <div class="container">
            <div class="row justify-content-center">
                <div class="media-container-column col-lg-8">
                    <!---Formbuilder Form--->
                    <form action="{% url 'new_order' sculpture.id %}" method="POST" class="mbr-form form-with-styler" id="FormNewOrder" data-form-type="formoid">
                        {% csrf_token %}
                        <input type="hidden" name="email" data-form-email="true" value="37YsNXDrDMp/JzINTq8KVG9RaVNuhw">
                        <div class="row">
                            <div hidden="hidden" data-form-alert="" class="alert alert-success col-12">Мы скоро свяжемся с Вами!</div>
                            <div hidden="hidden" data-form-alert-danger="" class="alert alert-danger col-12">
                            </div>
                        </div>
                        <div class="dragArea row">
                            <div class="col-md-4  form-group">
                                <label for="name-form1-1r" class="form-control-label mbr-fonts-style display-7">Имя</label>
                                <input type="text" name="first_name" data-form-field="Name" required="required" class="form-control display-7" id="name-form2">
                            </div>
                            <div class="col-md-4  form-group">
                                <label for="name-form1-1r" class="form-control-label mbr-fonts-style display-7">Фамилия</label>
                                <input type="text" name="last_name" required="" class="form-control display-7" id="name-form2">
                            </div>
                            <div data-for="phone" class="col-md-4  form-group">
                                <label for="phone-form1-1r" class="form-control-label mbr-fonts-style display-7">Телефон</label>
                                <input type="tel" name="phone" data-form-field="Phone" class="form-control display-7" id="phone-form2">
                            </div>
                            <div class="col-md-12  form-group" data-for="email">
                                <label for="email-form1-1r" class="form-control-label mbr-fonts-style display-7">Email</label>
                                <input type="email" name="email" data-form-field="Email" required="required" class="form-control display-7" id="email-form2">
                            </div>
                            <div data-for="message" class="col-md-12 form-group">
                                <label for="message-form1-1r" class="form-control-label mbr-fonts-style display-7">Сообщение</label>
                                <textarea name="text" class="form-control display-7" id="message-form2"></textarea>
                            </div>
                            <div class="col-md-12 input-group-btn align-center">
                                <button type="submit" class="btn btn-primary btn-form display-4">ОТПРАВИТЬ</button>
                            </div>
                        </div>
                    </form>
                    <!---Formbuilder Form--->
                </div>
            </div>
        </div>
    </section>

{% endblock content %}

templates/sculptures/portals_list.html
{% extends 'sculptures/base.html' %}

{% load static %}

{% block title %} Порталы {% endblock title %}

{%  block content %}

    <section class="mbr-section article content9 cid-rUKj6z2paH" id="content9-2v">
        <div class="container">
            <div class="inner-container" style="width: 100%;">
                <hr class="line" style="width: 25%;">
                <div class="section-text align-center mbr-fonts-style display-2">Порталы</div>
                <hr class="line" style="width: 25%;">
            </div>
        </div>
    </section>

    <section class="services1 cid-rW8nkLhdWM" id="services1-37">
        <div class="container">
            <div class="row justify-content-center">
                <div class="title pb-5 col-12"></div>

                {% for sculpture in sculpture_list %}

                    <div class="card col-12 col-md-6 p-3 col-lg-4">
                        <div class="card-wrapper">
                            <div class="card-img">
                                <img src="{{ sculpture.image_title.url }}" alt="">
                            </div>
                            <div class="card-box">
                                <h4 class="card-title mbr-fonts-style display-5">
                                    {{ sculpture.title }}
                                </h4>
                                <p class="mbr-text mbr-fonts-style display-7">
                                    Портал создан <br>
                                    {{ sculpture.year }}
                                </p>
                                <div class="mbr-section-btn align-center">
                                    <a href="{{ sculpture.get_absolute_url }}" class="btn btn-primary display-4">
                                        Подробнее
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>

                {% endfor %}

            </div>
        </div>
    </section>

{% endblock content %}

templates/sculptures/sitemap.html
{% extends 'sculptures/base.html' %}

{% block title %} О нас {% endblock title %}

{% load static %}

{% block content %}




{% endblock content %}